/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppCompareRouteImport } from './routes/_app/compare'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppReplayRouteImport } from './routes/_app/replay'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as SignupAdminRouteImport } from './routes/signup/admin'
import { Route as AppAdminClientsRouteImport } from './routes/_app/admin/clients'
import { Route as AppAdminDataSourcesRouteImport } from './routes/_app/admin/data-sources'
import { Route as AppAdminPortfoliosRouteImport } from './routes/_app/admin/portfolios'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppApprovalsIndexRouteImport } from './routes/_app/approvals/index'
import { Route as AppApprovalsInsightIdRouteImport } from './routes/_app/approvals/$insightId'
import { Route as AppApprovalsHistoryRouteImport } from './routes/_app/approvals/history'
import { Route as AppBanksSymbolRouteImport } from './routes/_app/banks.$symbol'
import { Route as AppScenariosIndexRouteImport } from './routes/_app/scenarios/index'
import { Route as AppScenariosHistoryRouteImport } from './routes/_app/scenarios/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppReplayRoute = AppReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAdminRoute = SignupAdminRouteImport.update({
  id: '/signup/admin',
  path: '/signup/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminClientsRoute = AppAdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDataSourcesRoute = AppAdminDataSourcesRouteImport.update({
  id: '/admin/data-sources',
  path: '/admin/data-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPortfoliosRoute = AppAdminPortfoliosRouteImport.update({
  id: '/admin/portfolios',
  path: '/admin/portfolios',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsIndexRoute = AppApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsInsightIdRoute = AppApprovalsInsightIdRouteImport.update({
  id: '/approvals/$insightId',
  path: '/approvals/$insightId',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsHistoryRoute = AppApprovalsHistoryRouteImport.update({
  id: '/approvals/history',
  path: '/approvals/history',
  getParentRoute: () => AppRoute,
} as any)
const AppBanksSymbolRoute = AppBanksSymbolRouteImport.update({
  id: '/banks/$symbol',
  path: '/banks/$symbol',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosIndexRoute = AppScenariosIndexRouteImport.update({
  id: '/scenarios/',
  path: '/scenarios/',
  getParentRoute: () => AppRoute,
} as any)
const AppScenariosHistoryRoute = AppScenariosHistoryRouteImport.update({
  id: '/scenarios/history',
  path: '/scenarios/history',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/account': typeof AppAccountRoute
  '/compare': typeof AppCompareRoute
  '/dashboard': typeof AppDashboardRoute
  '/explore': typeof AppExploreRoute
  '/replay': typeof AppReplayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/admin': typeof SignupAdminRoute
  '/admin/clients': typeof AppAdminClientsRoute
  '/admin/data-sources': typeof AppAdminDataSourcesRoute
  '/admin/portfolios': typeof AppAdminPortfoliosRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/approvals/$insightId': typeof AppApprovalsInsightIdRoute
  '/approvals/history': typeof AppApprovalsHistoryRoute
  '/banks/$symbol': typeof AppBanksSymbolRoute
  '/scenarios/history': typeof AppScenariosHistoryRoute
  '/approvals/': typeof AppApprovalsIndexRoute
  '/scenarios/': typeof AppScenariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/account': typeof AppAccountRoute
  '/compare': typeof AppCompareRoute
  '/dashboard': typeof AppDashboardRoute
  '/explore': typeof AppExploreRoute
  '/replay': typeof AppReplayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/admin': typeof SignupAdminRoute
  '/admin/clients': typeof AppAdminClientsRoute
  '/admin/data-sources': typeof AppAdminDataSourcesRoute
  '/admin/portfolios': typeof AppAdminPortfoliosRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/approvals/$insightId': typeof AppApprovalsInsightIdRoute
  '/approvals/history': typeof AppApprovalsHistoryRoute
  '/banks/$symbol': typeof AppBanksSymbolRoute
  '/scenarios/history': typeof AppScenariosHistoryRoute
  '/approvals': typeof AppApprovalsIndexRoute
  '/scenarios': typeof AppScenariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/replay': typeof AppReplayRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/signup/admin': typeof SignupAdminRoute
  '/_app/admin/clients': typeof AppAdminClientsRoute
  '/_app/admin/data-sources': typeof AppAdminDataSourcesRoute
  '/_app/admin/portfolios': typeof AppAdminPortfoliosRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/approvals/$insightId': typeof AppApprovalsInsightIdRoute
  '/_app/approvals/history': typeof AppApprovalsHistoryRoute
  '/_app/banks/$symbol': typeof AppBanksSymbolRoute
  '/_app/scenarios/history': typeof AppScenariosHistoryRoute
  '/_app/approvals/': typeof AppApprovalsIndexRoute
  '/_app/scenarios/': typeof AppScenariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/get-started'
    | '/login'
    | '/reset-password'
    | '/verify-otp'
    | '/account'
    | '/compare'
    | '/dashboard'
    | '/explore'
    | '/replay'
    | '/auth/callback'
    | '/signup/admin'
    | '/admin/clients'
    | '/admin/data-sources'
    | '/admin/portfolios'
    | '/admin/users'
    | '/approvals/$insightId'
    | '/approvals/history'
    | '/banks/$symbol'
    | '/scenarios/history'
    | '/approvals/'
    | '/scenarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/get-started'
    | '/login'
    | '/reset-password'
    | '/verify-otp'
    | '/account'
    | '/compare'
    | '/dashboard'
    | '/explore'
    | '/replay'
    | '/auth/callback'
    | '/signup/admin'
    | '/admin/clients'
    | '/admin/data-sources'
    | '/admin/portfolios'
    | '/admin/users'
    | '/approvals/$insightId'
    | '/approvals/history'
    | '/banks/$symbol'
    | '/scenarios/history'
    | '/approvals'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/get-started'
    | '/login'
    | '/reset-password'
    | '/verify-otp'
    | '/_app/account'
    | '/_app/compare'
    | '/_app/dashboard'
    | '/_app/explore'
    | '/_app/replay'
    | '/auth/callback'
    | '/signup/admin'
    | '/_app/admin/clients'
    | '/_app/admin/data-sources'
    | '/_app/admin/portfolios'
    | '/_app/admin/users'
    | '/_app/approvals/$insightId'
    | '/_app/approvals/history'
    | '/_app/banks/$symbol'
    | '/_app/scenarios/history'
    | '/_app/approvals/'
    | '/_app/scenarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SignupAdminRoute: typeof SignupAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/replay': {
      id: '/_app/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AppReplayRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/admin': {
      id: '/signup/admin'
      path: '/signup/admin'
      fullPath: '/signup/admin'
      preLoaderRoute: typeof SignupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/clients': {
      id: '/_app/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AppAdminClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/data-sources': {
      id: '/_app/admin/data-sources'
      path: '/admin/data-sources'
      fullPath: '/admin/data-sources'
      preLoaderRoute: typeof AppAdminDataSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/portfolios': {
      id: '/_app/admin/portfolios'
      path: '/admin/portfolios'
      fullPath: '/admin/portfolios'
      preLoaderRoute: typeof AppAdminPortfoliosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals/': {
      id: '/_app/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof AppApprovalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals/$insightId': {
      id: '/_app/approvals/$insightId'
      path: '/approvals/$insightId'
      fullPath: '/approvals/$insightId'
      preLoaderRoute: typeof AppApprovalsInsightIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals/history': {
      id: '/_app/approvals/history'
      path: '/approvals/history'
      fullPath: '/approvals/history'
      preLoaderRoute: typeof AppApprovalsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banks/$symbol': {
      id: '/_app/banks/$symbol'
      path: '/banks/$symbol'
      fullPath: '/banks/$symbol'
      preLoaderRoute: typeof AppBanksSymbolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenarios/': {
      id: '/_app/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof AppScenariosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenarios/history': {
      id: '/_app/scenarios/history'
      path: '/scenarios/history'
      fullPath: '/scenarios/history'
      preLoaderRoute: typeof AppScenariosHistoryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCompareRoute: typeof AppCompareRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExploreRoute: typeof AppExploreRoute
  AppReplayRoute: typeof AppReplayRoute
  AppAdminClientsRoute: typeof AppAdminClientsRoute
  AppAdminDataSourcesRoute: typeof AppAdminDataSourcesRoute
  AppAdminPortfoliosRoute: typeof AppAdminPortfoliosRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppApprovalsInsightIdRoute: typeof AppApprovalsInsightIdRoute
  AppApprovalsHistoryRoute: typeof AppApprovalsHistoryRoute
  AppBanksSymbolRoute: typeof AppBanksSymbolRoute
  AppScenariosHistoryRoute: typeof AppScenariosHistoryRoute
  AppApprovalsIndexRoute: typeof AppApprovalsIndexRoute
  AppScenariosIndexRoute: typeof AppScenariosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCompareRoute: AppCompareRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExploreRoute: AppExploreRoute,
  AppReplayRoute: AppReplayRoute,
  AppAdminClientsRoute: AppAdminClientsRoute,
  AppAdminDataSourcesRoute: AppAdminDataSourcesRoute,
  AppAdminPortfoliosRoute: AppAdminPortfoliosRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppApprovalsInsightIdRoute: AppApprovalsInsightIdRoute,
  AppApprovalsHistoryRoute: AppApprovalsHistoryRoute,
  AppBanksSymbolRoute: AppBanksSymbolRoute,
  AppScenariosHistoryRoute: AppScenariosHistoryRoute,
  AppApprovalsIndexRoute: AppApprovalsIndexRoute,
  AppScenariosIndexRoute: AppScenariosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SignupAdminRoute: SignupAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
