import { User, Bank, Client, Scenario, CfoInsight, PortfolioEntry, DataSourceSettings } from './types';

export const MOCK_USERS: (User & { password: string; is_active: boolean })[] = [
  {
    id: '1',
    name: 'Riya Sharma',
    email: 'analyst@finsight.demo',
    password: 'demo1234',
    role: 'analyst',
    avatar: '👩‍💼',
    is_active: true,
  },
  {
    id: '2',
    name: 'Arjun Mehta',
    email: 'cfo@finsight.demo',
    password: 'demo1234',
    role: 'cfo',
    avatar: '👨‍💼',
    is_active: true,
  },
  {
    id: '3',
    name: 'Vikram Patel',
    email: 'analyst2@finsight.demo',
    password: 'demo1234',
    role: 'analyst',
    avatar: '👨‍💻',
    is_active: true,
  },
  {
    id: '4',
    name: 'Priya Nair',
    email: 'admin@finsight.demo',
    password: 'demo1234',
    role: 'admin',
    avatar: '👩‍💻',
    is_active: true,
  },
];

export const mockUser: User = MOCK_USERS[0];

export const mockBanks: Bank[] = [
  {
    id: '1',
    name: 'Global Finance Corp',
    ticker: 'GFC',
    country: 'United States',
    headquarters: 'New York, NY',
    founded: 1995,
    employees: 45000,
    metrics: {
      totalAssets: 2850000,
      netIncome: 15200,
      capitalRatio: 14.2,
      loanToDepositRatio: 0.82,
      nonPerformingLoansRatio: 0.85,
      returnOnAssets: 0.53,
      returnOnEquity: 8.4,
      costToIncomeRatio: 0.58,
    },
    insights: [
      {
        id: '1',
        title: 'Strong Capital Position',
        description: 'Capital ratio exceeds regulatory requirements by 240 bps',
        severity: 'positive',
        source: 'regulatory',
        date: new Date('2025-08-01'),
        aiGenerated: true,
      },
      {
        id: '2',
        title: 'Rising Loan Portfolio',
        description: 'Loan-to-deposit ratio increased 3.2% YoY',
        severity: 'neutral',
        source: 'financial',
        date: new Date('2025-07-28'),
        aiGenerated: true,
      },
      {
        id: '3',
        title: 'Asset Quality Concern',
        description: 'NPL ratio trending higher; monitor closely',
        severity: 'warning',
        source: 'operational',
        date: new Date('2025-07-25'),
        aiGenerated: true,
      },
    ],
    badges: [
      { id: '1', label: 'Strong Capital', color: 'emerald', icon: '✓' },
      { id: '2', label: 'High Liquidity', color: 'blue', icon: '💧' },
      { id: '3', label: 'Watch NPL', color: 'amber', icon: '⚠️' },
    ],
  },
  {
    id: '2',
    name: 'European Banking Group',
    ticker: 'EBG',
    country: 'Germany',
    headquarters: 'Frankfurt am Main',
    founded: 1987,
    employees: 52000,
    metrics: {
      totalAssets: 3200000,
      netIncome: 18500,
      capitalRatio: 15.8,
      loanToDepositRatio: 0.75,
      nonPerformingLoansRatio: 1.2,
      returnOnAssets: 0.58,
      returnOnEquity: 9.2,
      costToIncomeRatio: 0.62,
    },
    insights: [
      {
        id: '4',
        title: 'Excellent Efficiency Metrics',
        description: 'Cost-to-income ratio improved 180 bps',
        severity: 'positive',
        source: 'operational',
        date: new Date('2025-08-02'),
        aiGenerated: true,
      },
      {
        id: '5',
        title: 'Regulatory Approval Pending',
        description: 'Awaiting ECB decision on capital requirements',
        severity: 'neutral',
        source: 'regulatory',
        date: new Date('2025-07-30'),
        aiGenerated: false,
      },
    ],
    badges: [
      { id: '4', label: 'Efficient Ops', color: 'emerald', icon: '⚡' },
      { id: '5', label: 'EU Regulated', color: 'blue', icon: '🇪🇺' },
    ],
  },
  {
    id: '3',
    name: 'Asia Pacific Bank',
    ticker: 'APB',
    country: 'Singapore',
    headquarters: 'Singapore',
    founded: 2001,
    employees: 28000,
    metrics: {
      totalAssets: 1850000,
      netIncome: 12100,
      capitalRatio: 16.5,
      loanToDepositRatio: 0.68,
      nonPerformingLoansRatio: 0.62,
      returnOnAssets: 0.65,
      returnOnEquity: 10.8,
      costToIncomeRatio: 0.48,
    },
    insights: [
      {
        id: '6',
        title: 'Outstanding ROE Performance',
        description: 'ROE at 10.8%, highest in regional peer group',
        severity: 'positive',
        source: 'financial',
        date: new Date('2025-08-03'),
        aiGenerated: true,
      },
      {
        id: '7',
        title: 'Digital Transformation Success',
        description: 'Digital channels now account for 65% of transactions',
        severity: 'positive',
        source: 'operational',
        date: new Date('2025-08-01'),
        aiGenerated: true,
      },
      {
        id: '8',
        title: 'Emerging Market Exposure',
        description: 'Portfolio diversification strategy yielding results',
        severity: 'neutral',
        source: 'market',
        date: new Date('2025-07-29'),
        aiGenerated: false,
      },
    ],
    badges: [
      { id: '6', label: 'Market Leader', color: 'emerald', icon: '🏆' },
      { id: '7', label: 'Digital Native', color: 'blue', icon: '💻' },
      { id: '8', label: 'Growth Region', color: 'emerald', icon: '📈' },
    ],
  },
  {
    id: '4',
    name: 'Canadian Financial Services',
    ticker: 'CFS',
    country: 'Canada',
    headquarters: 'Toronto, ON',
    founded: 1975,
    employees: 38000,
    metrics: {
      totalAssets: 2100000,
      netIncome: 13800,
      capitalRatio: 13.5,
      loanToDepositRatio: 0.79,
      nonPerformingLoansRatio: 0.95,
      returnOnAssets: 0.66,
      returnOnEquity: 9.1,
      costToIncomeRatio: 0.61,
    },
    insights: [
      {
        id: '9',
        title: 'Mortgage Portfolio Expansion',
        description: 'Mortgage lending grew 8.5% in H1 2025',
        severity: 'neutral',
        source: 'financial',
        date: new Date('2025-08-02'),
        aiGenerated: true,
      },
    ],
    badges: [
      { id: '9', label: 'Stable Growth', color: 'blue', icon: '📊' },
    ],
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    bankId: '1',
    bankName: 'Global Finance Corp',
    bankTicker: 'GFC',
    role: 'focus',
    addedDate: new Date('2025-06-01'),
  },
  {
    id: '2',
    bankId: '2',
    bankName: 'European Banking Group',
    bankTicker: 'EBG',
    role: 'peer',
    addedDate: new Date('2025-06-15'),
  },
  {
    id: '3',
    bankId: '3',
    bankName: 'Asia Pacific Bank',
    bankTicker: 'APB',
    role: 'peer',
    addedDate: new Date('2025-07-01'),
  },
];

export const mockCfoInsights: CfoInsight[] = [
  {
    id: 'cfo-1',
    company_name: 'Global Finance Corp',
    ticker: 'GFC',
    generated_text: 'Capital ratio exceeds regulatory requirements by 240 bps, demonstrating strong financial resilience and capacity for growth initiatives.',
    insight_type: 'Capital Strength',
    approval_status: 'pending',
    created_at: new Date('2025-08-04'),
    metric_types: ['Capital Ratio', 'Regulatory Requirements'],
  },
  {
    id: 'cfo-2',
    company_name: 'European Banking Group',
    ticker: 'EBG',
    generated_text: 'Cost-to-income ratio improved 180 bps, indicating significant operational efficiency gains and better cost management.',
    insight_type: 'Efficiency Gains',
    approval_status: 'pending',
    created_at: new Date('2025-08-03'),
    metric_types: ['Cost-to-Income Ratio', 'Operational Metrics'],
  },
  {
    id: 'cfo-3',
    company_name: 'Asia Pacific Bank',
    ticker: 'APB',
    generated_text: 'ROE at 10.8%, highest in regional peer group, reflecting superior profitability and effective capital deployment.',
    insight_type: 'Return on Equity',
    approval_status: 'approved',
    approved_at: new Date('2025-08-02'),
    created_at: new Date('2025-08-01'),
    metric_types: ['Return on Equity'],
  },
  {
    id: 'cfo-4',
    company_name: 'Global Finance Corp',
    ticker: 'GFC',
    generated_text: 'Loan-to-deposit ratio increased 3.2% YoY, suggesting expanded lending portfolio and potential liquidity optimization opportunities.',
    insight_type: 'Portfolio Expansion',
    approval_status: 'approved',
    approved_at: new Date('2025-08-01'),
    created_at: new Date('2025-07-28'),
    metric_types: ['Loan-to-Deposit Ratio'],
  },
  {
    id: 'cfo-5',
    company_name: 'Canadian Financial Services',
    ticker: 'CFS',
    generated_text: 'Mortgage lending grew 8.5% in H1 2025, indicating strong market demand and successful execution of growth strategy.',
    insight_type: 'Segment Growth',
    approval_status: 'approved',
    approved_at: new Date('2025-07-30'),
    created_at: new Date('2025-07-25'),
    metric_types: ['Mortgage Portfolio'],
  },
];

export const mockScenarios: Scenario[] = [
  {
    id: '1',
    name: 'Q3 Interest Rate Hike',
    description: 'Scenario modeling impact of 75 bps rate increase',
    bankId: '1',
    parameters: {
      assetChange: 0,
      incomeChange: 3.2,
      riskChange: -1.5,
      operationalChange: 0,
    },
    results: {
      capitalRatioChange: 0.8,
      profitabilityImpact: 2.1,
      riskScoreChange: -0.5,
      recommendations: [
        'Increase rate-sensitive asset allocation',
        'Consider hedging strategies',
        'Monitor deposit flight risk',
      ],
    },
    createdDate: new Date('2025-07-15'),
  },
  {
    id: '2',
    name: 'Economic Slowdown',
    description: 'Stress test for recession scenario',
    bankId: '1',
    parameters: {
      assetChange: -5.0,
      incomeChange: -8.5,
      riskChange: 6.0,
      operationalChange: -2.0,
    },
    results: {
      capitalRatioChange: -2.1,
      profitabilityImpact: -6.8,
      riskScoreChange: 5.2,
      recommendations: [
        'Review credit underwriting standards',
        'Build additional loan loss reserves',
        'Reduce leverage',
      ],
    },
    createdDate: new Date('2025-07-20'),
  },
];

export const mockPortfolios: PortfolioEntry[] = [
  {
    id: 'p1',
    client_name: 'TechCorp Investment Fund',
    company_id: '1',
    bank_name: 'Global Finance Corp',
    ticker: 'GFC',
    uploaded_by: 'Priya Nair',
  },
  {
    id: 'p2',
    client_name: 'TechCorp Investment Fund',
    company_id: '3',
    bank_name: 'European Banking Group',
    ticker: 'EBG',
    uploaded_by: 'Priya Nair',
  },
  {
    id: 'p3',
    client_name: 'Pension Reserve Admin',
    company_id: '2',
    bank_name: 'Asia Pacific Bank',
    ticker: 'APB',
    uploaded_by: 'Priya Nair',
  },
  {
    id: 'p4',
    client_name: 'Pension Reserve Admin',
    company_id: '4',
    bank_name: 'Canadian Financial Services',
    ticker: 'CFS',
    uploaded_by: 'Priya Nair',
  },
];

export const mockDataSourceSettings: DataSourceSettings = {
  api_key: 'sk_test_12345abcde67890fghijk',
  last_connection_test: new Date('2025-08-04T10:30:00Z'),
  connection_status: 'connected',
};
